CREATE TABLE [TABELA DE PRODUTOS]
([CODIGO DO PRODUTO] [VARCHAR] (20),
[NOME DO PRODUTO] [VARCHAR] (150),
[EMBALAGEM] [VARCHAR] (50),
[TAMANHO] [VARCHAR] (50),
[SABOR] [VARCHAR] (50),
[PRECO DE LISTA] [SMALLMONEY]); 