CREATE DATABASE SUCOS_VENDAS
ON (NAME = 'SUCOS_VENDAS_DAT',
	FILENAME = 'C:\Banco de dados\SALES_VENDAS_SUCOS.MDF',
	SIZE = 10MB,
	MAXSIZE = 100MB,
	FILEGROWTH = 5MB )
LOG ON (NAME = 'SUCOS_VENDAS.LOG',
	FILENAME = 'C:\Banco de dados\SALES_VENDAS_SUCOS.LDF',
	SIZE = 10MB,
	MAXSIZE = 100MB,
	FILEGROWTH = 5MB );

