SELECT LTRIM('                 Olá  Mundo')

SELECT RTRIM('Aprendendo SQL                  ')

SELECT CONCAT('Olá mundo ','estou aprendendo SQL Server')

SELECT 'Olá mundo ' + 'estou aprendendo SQL Server'

--PEGA AS 3 PALAVRAS DA ESQUERDA
SELECT LEFT ('Rua Prefeito José Basilio Alvarenga', 3)

--PEGA AS 10 PALAVRAS DA DIREITA
SELECT RIGHT('Rua Prefeito José Basilio Alvarenga', 10)

SELECT UPPER('marcel moura da luz melo')

SELECT LOWER('MARCEL MOURA DA LUZ MELO')

SELECT REPLACE('R: PREFEITO JOSE BASILIO ALVARENGA','R:','RUA')

--O PRIMEIRO VALOR SELECIONA A POISÇÃO DA STRING  E SEGUNDO VALOR É A QUANTIDADE 
SELECT SUBSTRING('MARCEL MOURA DA LUZ MELO', 1, 6)

SELECT LEN('MARCEL MOURA DA LUZ MELO')

SELECT CONCAT(NOME, ' (', CPF, ') ') FROM [TABELA DE CLIENTES]


--FUNÇÕES PARA DATAS E HORARIOS
SELECT SYSDATETIME()

SELECT SYSDATETIMEOFFSET()

SELECT SYSUTCDATETIME()

SELECT CURRENT_TIMESTAMP

SELECT GETDATE()

SELECT GETUTCDATE()

SELECT DATENAME(YEAR, GETDATE())

SELECT DATENAME(MICROSECOND, GETDATE())

SELECT DATENAME(MONTH, GETDATE())

SELECT DATEPART(MONTH, GETDATE())

SELECT DAY(GETDATE())

SELECT YEAR(GETDATE())

SELECT DATEFROMPARTS(2016,7,22)


--FUNÇÕES MATEMÁTICAS
SELECT CEILING(12.333223)

SELECT FLOOR(12.333233)

SELECT RAND()

SELECT ROUND(12.33323323, 2)

--CONVERSÃO DE DADOS
SELECT CONVERT(VARCHAR, GETDATE(), 101)

SELECT CONVERT(VARCHAR, GETDATE(), 113)

SELECT CONVERT(DECIMAL(10,5), 193.57)


SELECT 'O preço do produto ' + [NOME DO PRODUTO] + ' é ' + 'R$ ' + CONVERT(VARCHAR,[PRECO DE LISTA])
FROM [TABELA DE PRODUTOS]