INSERT INTO [TABELA DE VENDEDORES]
([MATRICULA], [NOME], [PERCENTUAL COMISSAO])
VALUES
('00235', 'Márcio Almeida Silva', 0.08),
('00236', 'Cláudia Morais', 0.08)

INSERT INTO [TABELA DE VENDEDORES]
([MATRICULA], [NOME], [PERCENTUAL COMISSAO])
VALUES
('00237', 'Roberta Martins', 0.11),
('00238', 'Pericles Alves', 0.07)

UPDATE [TABELA DE VENDEDORES]
SET [PERCENTUAL COMISSAO] = 0.11
WHERE [MATRICULA] = '00235'

UPDATE [TABELA DE VENDEDORES]
SET [NOME] = 'Cláudia Morais Sousa'
WHERE [MATRICULA] = '00236'

DELETE FROM [TABELA DE VENDEDORES]
WHERE [MATRICULA] = ''

ALTER TABLE [TABELA DE VENDEDORES]
ALTER COLUMN [MATRICULA]
VARCHAR (5) NOT NULL;

ALTER TABLE [TABELA DE VENDEDORES]
ADD CONSTRAINT PK_TABELA_DE_VENDEDORES
PRIMARY KEY CLUSTERED ([MATRICULA])

ALTER TABLE [TABELA DE VENDEDORES]
ALTER COLUMN [PERCENTUAL COMISSAO]
FLOAT NOT NULL;

SELECT [MATRICULA] AS IDENTIFICADOR, [NOME] AS [NOME DO VENDENDOR] FROM [TABELA DE VENDEDORES]