SELECT SUM(QUANTIDADE * [PREÇO]) FROM [ITENS NOTAS FISCAIS] WHERE
NUMERO = 100

CREATE FUNCTION FaturamentoNota (@NUMERO AS INT) RETURNS FLOAT AS
BEGIN
	DECLARE @FATURAMENTO FLOAT
	SELECT @FATURAMENTO = SUM(QUANTIDADE * [PREÇO]) FROM [ITENS NOTAS FISCAIS]
	WHERE NUMERO = @NUMERO
	RETURN @FATURAMENTO
END

SELECT NUMERO, [dbo].[FaturamentoNota] (NUMERO) AS FATURAMENTO FROM [NOTAS FISCAIS]
----------------------------------------------------------------------------------------
CREATE FUNCTION NumeroNotas (@DATA DATE) RETURNS INT AS
BEGIN
	DECLARE @NUMNOTAS INT 
	SELECT @NUMNOTAS = COUNT(*) FROM [NOTAS FISCAIS]
	WHERE DATA = @DATA
	RETURN @NUMNOTAS
END

SELECT [dbo].[NumeroNotas] ('20170202')
--------------------------------------------------------------------------------------------
CREATE FUNCTION ListaNotasCliente (@CPF AS VARCHAR (12)) RETURNS TABLE AS
RETURN SELECT * FROM [NOTAS FISCAIS] WHERE CPF = @CPF

SELECT * FROM [dbo].[ListaNotasCliente]('1471156710')
-------------------------------------------------------------------------------------------
CREATE FUNCTION EnderecoCompleto (@ENDERECO VARCHAR (100), @CIDADE VARCHAR (50),
@ESTADO VARCHAR (50), @CEP VARCHAR(20)) RETURNS VARCHAR (250) AS
BEGIN
	DECLARE @ENDERECO_COMPLETO VARCHAR (250)
	SET @ENDERECO_COMPLETO = @ENDERECO + ' - ' + @CIDADE + ' - ' + @ESTADO + ' - ' + @CEP
	RETURN @ENDERECO_COMPLETO
END

SELECT CPF, [dbo].[EnderecoCompleto]([ENDERECO 1], CIDADE, ESTADO, CEP) AS END_COMPLETO
FROM [TABELA DE CLIENTES]

ALTER FUNCTION EnderecoCompleto (@ENDERECO VARCHAR (100), @CIDADE VARCHAR (50),
@ESTADO VARCHAR (50), @CEP VARCHAR(20)) RETURNS VARCHAR (250) AS
BEGIN
	DECLARE @ENDERECO_COMPLETO VARCHAR (250)
	SET @ENDERECO_COMPLETO = @ENDERECO + ', ' + @CIDADE + ', ' + @ESTADO + ', ' + @CEP
	RETURN @ENDERECO_COMPLETO
END
---------------------------------------------------------------------------------------------