UPDATE TABELA_PRODUTOS SET PRECO_LISTA = 5 WHERE CODIGO = '1040107'
--------------------------------------------------------------------------------------
UPDATE TABELA_PRODUTOS SET PRECO_LISTA = PRECO_LISTA * 1.10
WHERE SABOR = 'Maracujá'

SELECT * FROM TABELA_PRODUTOS WHERE SABOR = 'Maracujá'
--------------------------------------------------------------------------------------
UPDATE TABELA_CLIENTES SET 
ENDERECO = 'R. Jorge Emilio 23',
BAIRRO = 'Santo Amaro',
CIDADE = 'São Paulo',
ESTADO = 'SP',
CEP = '8833223' WHERE CPF = '19290992743'

SELECT * FROM TABELA_CLIENTES WHERE CPF = '19290992743' 
--------------------------------------------------------------------------------------
UPDATE TABELA_CLIENTES SET
VOLUME_COMPRA = VOLUME_COMPRA * 1.20 WHERE ESTADO = 'RJ'

SELECT * FROM TABELA_CLIENTES WHERE ESTADO = 'RJ'
--------------------------------------------------------------------------------------
SELECT * FROM SUCOS_VENDAS.DBO.[TABELA DE PRODUTOS]
WHERE [CODIGO DO PRODUTO] = '1000889'

SELECT * FROM TABELA_PRODUTOS WHERE CODIGO = '1000889'
--------------------------------------------------------------------------------------
UPDATE SUCOS_VENDAS.DBO.[TABELA DE PRODUTOS] SET [PREÇO DE LISTA] = 7
WHERE [CODIGO DO PRODUTO] = '1000889'
--------------------------------------------------------------------------------------
SELECT B.[CODIGO DO PRODUTO], B.[PREÇO DE LISTA], A.CODIGO, A.PRECO_LISTA 
FROM TABELA_PRODUTOS A INNER JOIN [SUCOS_VENDAS].DBO.[TABELA DE PRODUTOS] B ON
A.CODIGO = B.[CODIGO DO PRODUTO] WHERE A.CODIGO = '10000889'

UPDATE A SET A.PRECO_LISTA = B.[PREÇO DE LISTA] FROM TABELA_PRODUTOS A INNER JOIN
[SUCOS_VENDAS].DBO.[TABELA DE PRODUTOS] B ON A.CODIGO = B.[CODIGO DO PRODUTO]
WHERE A.CODIGO = '1000889'

SELECT B.[CODIGO DO PRODUTO], B.[PREÇO DE LISTA], 
A.CODIGO, A.PRECO_LISTA FROM TABELA_PRODUTOS A 
INNER JOIN [SUCOS_VENDAS].[DBO].[TABELA DE PRODUTOS] B 
 ON A.CODIGO = B.[CODIGO DO PRODUTO]
WHERE A.CODIGO = '1000889'
--------------------------------------------------------------------------------------
UPDATE [SUCOS_VENDAS].DBO.[TABELA DE PRODUTOS] SET [PREÇO DE LISTA] = 8
WHERE [CODIGO DO PRODUTO] = '1002334'

SELECT B.[CODIGO DO PRODUTO], B.[PREÇO DE LISTA], A.CODIGO, A.PRECO_LISTA FROM
TABELA_PRODUTOS A INNER JOIN [SUCOS_VENDAS].DBO.[TABELA DE PRODUTOS] B ON
A.CODIGO = B.[CODIGO DO PRODUTO] WHERE CODIGO = '1002334'

MERGE INTO TABELA_PRODUTOS A USING [SUCOS_VENDAS].DBO.[TABELA DE PRODUTOS] B ON
A.CODIGO = B.[CODIGO DO PRODUTO] AND A.CODIGO = '1002334' WHEN MATCHED THEN
UPDATE SET A.PRECO_LISTA = B.[PREÇO DE LISTA];

SELECT B.[CODIGO DO PRODUTO], B.[PREÇO DE LISTA], A.CODIGO, A.PRECO_LISTA FROM
TABELA_PRODUTOS A INNER JOIN [SUCOS_VENDAS].DBO.[TABELA DE PRODUTOS] B ON 
A.CODIGO = B.[CODIGO DO PRODUTO] WHERE CODIGO = '1002334'
--------------------------------------------------------------------------------------