CREATE DATABASE VENDAS_SUCOS ON (NAME = VENDAS_SUCOS_DAT,
FILENAME ='C:\Banco de dados\Vendas_sucos\VENDAS_SUCOS.MDF',
SIZE = 10MB, MAXSIZE = 50MB, FILEGROWTH = 5MB)
LOG ON (NAME = VENDAS_SUCOS_LOG, FILENAME = 'C:\Banco de dados\Vendas_sucos\VENDAS_SUCOS.LDF',
SIZE = 10MB, MAXSIZE = 50MB, FILEGROWTH = 5MB)