INSERT INTO TABELA_CLIENTES
(CPF, NOME, ENDERECO, BAIRRO, CIDADE, ESTADO, CEP, DATA_NASCIMENTO, IDADE, SEXO,
LIMITE_CREDITO, VOLUME_COMPRA, PRIMEIRA_COMPRA)
SELECT CPF, NOME, [ENDERECO 1] AS ENDERECO, BAIRRO, CIDADE, ESTADO, CEP, 
[DATA DE NASCIMENTO] AS DATA_NASCIMENTO, IDADE, SEXO, [LIMITE DE CREDITO] AS LIMITE_CREDITO,
[VOLUME DE COMPRA] AS VOLUME_COMPRA, [PRIMEIRA COMPRA] AS PRIMEIRA_COMPRA FROM 
[SUCOS_VENDAS].[DBO].[TABELA DE CLIENTES] WHERE CPF NOT IN ('1471156710', '19290992743',
'2600586709')