
INSERT INTO TABELA_PRODUTOS
(CODIGO, DESCRITOR, SABOR, TAMANHO, EMBALAGEM, PRECO_LISTA)
SELECT [CODIGO DO PRODUTO] AS CODIGO, [NOME DO PRODUTO] AS DESCRITOR, 
[SABOR] AS SABOR, [TAMANHO] AS TAMANHO, [EMBALAGEM] AS EMBALAGEM,
[PREÇO DE LISTA] AS PRECO_LISTA FROM [SUCOS_VENDAS].[DBO].[TABELA DE PRODUTOS] 
WHERE [CODIGO DO PRODUTO] <> '1040107'