CREATE TABLE TABELA_ITENS
(NUMERO VARCHAR (5) NOT NULL, CODIGO_PRODUTO VARCHAR (10) NULL, 
QUANTIDADE FLOAT, PRECO FLOAT,
CONSTRAINT PK_TABELA_ITENS PRIMARY KEY (NUMERO))

ALTER TABLE TABELA_ITENS WITH CHECK ADD CONSTRAINT FK_ITENS_VENDIDOS_PRODUTOS
FOREIGN KEY (CODIGO_PRODUTO) REFERENCES TABELA_PRODUTOS (CODIGO)

ALTER TABLE TABELA_ITENS WITH CHECK ADD CONSTRAINT FK_VENDAS_ITENS
FOREIGN KEY (NUMERO) REFERENCES TABELA_NOTAS (NUMERO)