CREATE TABLE TABELA_CLIENTES
(CPF VARCHAR (11) NOT NULL, NOME VARCHAR (100) NULL, ENDERECO VARCHAR (150) NULL,
BAIRRO VARCHAR (50) NULL, CIDADE VARCHAR (50) NULL, ESTADO VARCHAR (50) NULL,
CEP VARCHAR (8) NULL, DATA_NASCIMENTO DATE NULL, IDADE INT NULL, SEXO VARCHAR (1),
LIMITE_CREDITO FLOAT NULL, VOLUME_COMPRA FLOAT NULL, PRIMEIRA_COMPRA BIT NULL,
CONSTRAINT PK_TABELA_CLIENTES PRIMARY KEY (CPF))