CREATE TABLE TABELA_PRODUTOS
(CODIGO VARCHAR (10) NOT NULL, DESCRITOR VARCHAR (100) NULL,
SABOR VARCHAR (50) NULL, TAMANHO VARCHAR (50) NULL, 
EMBALAGEM VARCHAR (50) NULL, PRECO_LISTA FLOAT NULL,
CONSTRAINT PK_TABELA_PRODUTOS PRIMARY KEY(CODIGO))