CREATE TABLE TAB_CHECK
(ID INT NOT NULL, NOME VARCHAR (20) NULL, IDADE INT NULL, CIDADE VARCHAR (20) NULL,
CONSTRAINT CHK_PESSOA CHECK (IDADE >= 18))

INSERT INTO TAB_CHECK (ID, NOME, IDADE, CIDADE) VALUES
(1, 'João', 19 , 'São Paulo')
INSERT INTO TAB_CHECK (ID, NOME, IDADE, CIDADE) VALUES
(2, 'Pedro', 17, 'Santa Catarina')